services:
  pg_lucia:
    image: postgres:15-alpine
    container_name: pg_lucia_auth_container
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer_lucia_auth_container
    restart: always
    ports:
      - 8080:8080

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog_lucia_auth_container
    ports:
      - 8025:8025
      - 1025:1025

volumes:
  postgres-data:
